apiVersion: v1
kind: Pod
metadata:
  name: quiz
spec:
  volumes:
    - name: quiz-data
      emptyDir:
        {}
  containers:
  - name: quiz-api
    image: luksa/quiz-api:0.1
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8080
  - name: mongo
    image: mongo:5.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /data/db
        name: quiz-data
        readOnly: false


