apiVersion: v1
kind: Pod
metadata:
  name: quote-poststart-fail
spec:
  restartPolicy: OnFailure
  containers:
    - name: nginx
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - "echo 'Emulating a post-start hook failure'; exit 1"
