apiVersion: v1
kind: Pod
metadata:
  name: mongodb-local-ssd
spec:
  volumes:
    - name: mongodb-data
      persistentVolumeClaim:
        claimName: pvc-local-ssd
  containers:
    - image: mongo
      name: mongodb
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db