apiVersion: v1
kind: Pod
metadata:
  name: kiada-pod-cfmap-volume
spec:
  volumes:
    - name: envoy-config
      configMap:
        defaultMode: 0740
        name: kiada-envoy-config
        items:
          - key: envoy.yaml
            path: envoy.yaml
  containers:
    - name: kiada-cfmap
      image: luksa/kiada:0.4
      imagePullPolicy: IfNotPresent
      command:
        - node
        - app.js
      args:
        - "--listen-port"
        - "9090"
      ports:
        - containerPort: 8080
          name: http
    - name: envoy
      image: luksa/kiada-ssl-proxy:0.1
      volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
          readOnly: true
      ports:
        - name: https
          containerPort: 8443
        - name: admin
          containerPort: 9901