apiVersion: v1
kind: Pod
metadata:
  name: quote-poststart-slow
spec:
  restartPolicy: OnFailure
  containers:
    - name: nginx
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - |
                apk add fortune && \
                sleep 60 && \
                curl -O https://luksa.github.io/kiada/book-quotes.txt && \
                curl -O https://luksa.github.io/kiada/book-quotes.txt.dat && \
                fortune book-quotes.txt > /usr/share/nginx/html/quote
