apiVersion: v1
kind: Pod
metadata:
  name: kiada-ssl
spec:
  containers:
    - name: kiada
      image: luksa/kiada:0.2
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
    - name: envoy
      image: luksa/kiada-ssl-proxy:0.1
      imagePullPolicy: Always
      ports:
        - containerPort: 8443
          name: https
        - containerPort: 9901
          name: admin