apiVersion: v1
kind: Pod
metadata:
  name: kiada-pod-downwarm-api
spec:
  containers:
    - name: kiada
      image: luksa/kiada:0.4
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP