apiVersion: v1
kind: Service
metadata:
  name: kiada-svc-loadbalancer
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: kiada
  ports:
    - name: http
      port: 80
      nodePort: 30070
      targetPort: 8080
    - name: https
      port: 443
      nodePort: 31443
      targetPort: 8443