apiVersion: v1
kind: Service
metadata:
  name: kiada-svc
  labels:
    type: nodeport
spec:
  selector:
    app: kiada
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      nodePort: 30443
      targetPort: 8443