apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: kiada-ns
  labels:
    type: svc-quiz
spec:
  type: ClusterIP
  selector:
    app: quiz
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
