apiVersion: v1
kind: Service
metadata:
  name: quote-headless-svc
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: kiada
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 80