apiVersion: v1
kind: Service
metadata:
  name: quote-cname-svc
spec:
  type: ExternalName
  externalName: worldtimeapi.org
#  ports:
#    - name: http
#      port: 80
#      targetPort: http
#      protocol: TCP