apiVersion: v1
kind: Service
metadata:
  name: quote-service
  namespace: kiada-ns
  labels:
    type: svc-quote
spec:
  type: ClusterIP
  selector:
    app: quote
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
