apiVersion: v1
kind: Service
metadata:
  name: quote-internal-svc
spec:
  type: ClusterIP
  internalTrafficPolicy: Local
  selector:
    app: quote
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP