apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-pvc-expression
  labels:
    type: ssd-claim
spec:
  storageClassName: local-ssd
  resources:
    requests:
      storage: 1Gi
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - ssd
      - key: type
        operator: Exists
      - key: age
        operator: NotIn
        values:
          - old
          - very-old