apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:stable-bullseye
          imagePullPolicy: Always
          restartPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
