apiVersion: v1
kind: Service
metadata:
  name: quiz-po
  labels:
    app: quiz
    rel: stable
spec:
  selector:
    app: quiz
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mongodb
      port: 27017