apiVersion: v1
kind: Service
metadata:
  name: node-agent-svc
  labels:
    app: node-agent-svc
spec:
  selector:
    app: node-agent
  type: ClusterIP
  internalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      targetPort: 80
